---
- name: Check user
  command: /usr/bin/getent passwd {{ wp_owner | quote }}
  failed_when: false
  changed_when: false
  register: user_check

- name: Check group
  command: /usr/bin/getent group {{ wp_group | quote }}
  failed_when: false
  changed_when: false
  register: group_check

- name: Assert user {{ wp_owner }} exists
  assert:
    that: user_check.rc == 0
    fail_msg: User {{ wp_owner }} does not exist on this system.

- name: Assert group {{ wp_group }} exists
  assert:
    that: group_check.rc == 0
    fail_msg: Group {{ wp_group }} does not exist on this system.

- name: Assert required installation variables are set
  assert:
    that: lookup("vars", item, default=False)
    fail_msg: Required variable {{ item }} is not set.
  loop:
  - wp_url
  - wp_admin_email
  when: not wp_skip_install
